// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvMaze.Scraper.Data;

#nullable disable

namespace TvMaze.Scraper.Data.Migrations
{
    [DbContext(typeof(TvMazeDataContext))]
    [Migration("20221130180952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PersonTvShow", b =>
                {
                    b.Property<int>("CastMembersPersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cast_members_person_id");

                    b.Property<int>("TvShowsTvShowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tv_shows_tv_show_id");

                    b.HasKey("CastMembersPersonId", "TvShowsTvShowId")
                        .HasName("pk_person_tv_show");

                    b.HasIndex("TvShowsTvShowId")
                        .HasDatabaseName("ix_person_tv_show_tv_shows_tv_show_id");

                    b.ToTable("person_tv_show", (string)null);
                });

            modelBuilder.Entity("TvMaze.Scraper.Data.Model.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT")
                        .HasColumnName("birthday");

                    b.Property<uint>("LastUpdated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("PersonId")
                        .HasName("pk_people");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("TvMaze.Scraper.Data.Model.TvShow", b =>
                {
                    b.Property<int>("TvShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tv_show_id");

                    b.Property<uint>("LastUpdated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("TvShowId")
                        .HasName("pk_tv_shows");

                    b.ToTable("tv_shows", (string)null);
                });

            modelBuilder.Entity("PersonTvShow", b =>
                {
                    b.HasOne("TvMaze.Scraper.Data.Model.Person", null)
                        .WithMany()
                        .HasForeignKey("CastMembersPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_tv_show_people_cast_members_person_id");

                    b.HasOne("TvMaze.Scraper.Data.Model.TvShow", null)
                        .WithMany()
                        .HasForeignKey("TvShowsTvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_tv_show_tv_shows_tv_shows_tv_show_id");
                });
#pragma warning restore 612, 618
        }
    }
}
